### ISSUE TITLE
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-native-template-react-native-template-daf - Not found

### ISSUE THREAD

**Issue by Muhammad-Altabba** [uport-project/daf-templates#1]
When running the command `npx react-native init MyDafProject --template react-native-template-daf` it gives an error:

> npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-native-template-react-native-template-daf - Not found

I noticed that the package exists at https://registry.npmjs.org/react-native-template-daf exists. But the actually requested package that causes the error does not. Actually the url in the error has `react-native-template-` twice!

I am running the command on Linux Mint.

**Comment by jasonhealy** [comment]
@Muhammad-Altabba  Thanks for reporting. 

Please remove your global install of `react-native` and try again.

**Comment by Muhammad-Altabba** [comment]
Dear @jasonhealy, I would like to keep my global `react-native`. Is there another way to overcome this issue. (And I do not know how a wrong URL could be because of a global react-native being installed)

**Comment by jasonhealy** [comment]
You can always update your global dependency to the latest version. I believe the issue is because of a version mismatch. Using `npx` will always use the latest version. We try to keep inline with what React Native recommend on their docs.
